## Configuracion de Spring
spring:
  application:
    name: ms-books-catalogue
#  datasource:
#    url: jdbc:h2:mem:testdb;Mode=MySQL
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true

## Configuracion de Instancia 
server:
  port: 8088
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue

##OpenSearch config
# opensearch:
#   host: ${OPENSEARCH_HOST}
#   credentials:
#     user: ${OPENSEARCH_USER}
#     password: ${OPENSEARCH_PWD}
# logging:
#   level:
#     tracer: TRACE

##OpenSearch config
opensearch:
  host: confident-poplar-1mjtqgk8.eu-west-1.bonsaisearch.net
  credentials:
    user: 2fe7550015
    password: 86b64f742ee5eaadfd81